export const search = [
  'id',
  'user_created',
  'date_created',
  'user_updated',
  'date_updated',
  'name',
  'code',
  'slug',
  'enabled',
  'new',
  'sale',
  'categories'
];
export const show = [];
export const read = [];
export const edit = [
  'id',
  'user_created',
  'date_created',
  'user_updated',
  'date_updated',
  'name',
  'code',
  'slug',
  'company',
  'api_code',
  'api_id',
  'enabled',
  'new',
  'categories.id',
  'categories.index',
  'categories.category',
  'seo_title',
  'seo_description',
  'description',
  'price_view',
  'show_price',
  'sale',
  'custom_prices_with_labeling',
  'custom_prices.id',
  'custom_prices.enabled',
  'custom_prices.amount',
  'custom_prices.price',
  'custom_prices_sale.id',
  'custom_prices_sale.enabled',
  'custom_prices_sale.amount',
  'custom_prices_sale.price',
  'labelings.id',
  'labelings.index',
  'labelings.enabled',
  'labelings.global_margin',
  'labelings.margin',
  'labelings.minimum',
  'labelings.labeling',
  'labelings.prices.id',
  'labelings.prices.enabled',
  'labelings.prices.amount',
  'labelings.prices.price',
  'labelings.prices_sale.id',
  'labelings.prices_sale.enabled',
  'labelings.prices_sale.amount',
  'labelings.prices_sale.price',
  'price',
  'price_sale',
  'price_sale_blacklist',
  'global_full_margin',
  'full_margin',
  'full_minimum',
  'global_product_margin',
  'product_margin',
  'product_minimum',
  'storage.id',
  'storage.index',
  'storage.enabled',
  'storage.amount',
  'storage.color_first',
  'storage.color_second',
  'storage.multicolored',
  'storage.api_color_code',
  'storage.img.id',
  'storage.img.index',
  'storage.img.enabled',
  'storage.img.img',
  'storage.img.show_in_gallery',
  'gallery.id',
  'gallery.index',
  'gallery.enabled',
  'gallery.main',
  'gallery.img',
  'recommendations.id',
  'recommendations.index',
  'recommendations.recommendation'
];

export const calculate = [
  'id',
  'price_view',
  'sale',
  'labelings.id',
  'labelings.enabled',
  'labelings.global_margin',
  'labelings.margin',
  'labelings.minimum',
  'labelings.labeling',
  'labelings.prices.id',
  'labelings.prices_sale.id',
  'price',
  'price_sale',
  'price_sale_blacklist',
  'global_full_margin',
  'full_margin',
  'full_minimum',
  'global_product_margin',
  'product_margin',
  'product_minimum'
];

export const defaults = () => ({
  id: '+',
  user_updated: null,
  date_updated: null,
  user_created: null,
  date_created: null,
  name: '',
  code: '',
  slug: '',
  company: null,
  api_code: '',
  api_id: '',
  enabled: true,
  new: false,
  categories: [],
  seo_title: '',
  seo_description: '',
  description: '',
  prices_view: null,
  show_price: true,
  sale: false,
  custom_prices_with_labeling: false,
  custom_prices: [],
  custom_prices_sale: [],
  labelings: [],
  price: 0,
  price_sale: 0,
  price_sale_blacklist: [],
  global_full_margin: false,
  full_margin: 0,
  full_minimum: 0,
  global_product_margin: true,
  product_margin: 0,
  product_minimum: 0,
  storage: [],
  gallery: [],
  recommendations: []
});

export default { search, show, read, edit, defaults };
