// What changed for the admins, newest first: every update gets a version here (shown at the bottom of the menu, the
// changelog opens by itself after a new one). X.Y.Z: Y - something new or noticeably different, Z - a fix, a tweak,
// or work nobody sees. `date`: YYYY-MM-DD.
//   { version, date, title, synopsis, changes }
// a change is its text, or { label, text, big }: a short name before it ("Historia zmian: ...", no colon after a dot:
// "P.S. ..."), bold when `big`
export const changelog = [
  {
    version: '1.28.1',
    date: '2026-10-04',
    title: 'Poprawki w kalkulacjach',
    synopsis: 'dół tabeli znakowań i ramka zaznaczonej komórki.',
    changes: [
      {
        label: 'Poprawka',
        text: 'krótka tabela znakowań kończy się na ostatnim wierszu, bez szarego paska pod spodem.',
      },
      'Zaznaczona komórka w tabelach ma cienką, jasnoniebieską ramkę widoczną ze wszystkich stron.',
    ],
  },
  {
    version: '1.28.0',
    date: '2026-10-04',
    title: 'Nowy wygląd panelu',
    synopsis: 'panel jest teraz w kratkę, a strona główna ładuje się szybciej.',
    changes: [
      {
        label: 'Nowy wygląd',
        text: 'panel wygląda jak formularz na macie do cięcia, a wszystko leży równo na jej kratce.',
        big: true,
      },
      'To nie tylko wygląd: układ jest gęstszy, więc gęstość informacji jest większa.',
      'Listy pokazują domyślnie 50 pozycji na stronę.',
      {
        label: 'Kalkulacje',
        text: 'po tabeli znakowań chodzi się strzałkami jak w Excelu; Enter edytuje, Esc cofa zmianę.',
        big: true,
      },
      'Zmienione komórki są żółte, a pod tabelą widać, które znakowania się zmieniły.',
      'W wyborze pliku „Wyczyść” zmienia się w „Przywróć”, a wyczyszczony kafelek ma przerywaną ramkę.',
      'W API › Produkty można zmienić firmę, zanim skończy się pobieranie danych.',
      'Notatki w produkcie wypełniają kolumnę i są żółte, gdy coś zawierają.',
      {
        label: 'Poprawka',
        text: 'kategorię dodaną ręcznie można usunąć przed zapisem, nawet gdy jest w mapowaniu API.',
      },
      { label: 'Poprawka', text: 'przełączniki znakowań i wariantów oraz pola wyboru już nie migają.' },
      {
        label: 'Strona',
        text: 'wiele różnych optymalizacji, dzięki czemu strona główna ładuje się szybciej.',
        big: true,
      },
      {
        label: 'Uwaga',
        text: 'zmiany na stronie głównej, w Kontakcie, politykach, kategoriach i stopce klienci mogą zobaczyć do 5 minut później – wejścia na stronę są zapisywane w pamięci podręcznej, żeby przyspieszyć wczytywanie.',
      },
      'Wizyty z przeglądarek, w których admin logował się do panelu, nie liczą się już do statystyk strony.',
      {
        label: 'Drobne zmiany',
        text: '„Anuluj” w wyborze pliku to „Wróć”, znaczki skanera w opcjach są mniejsze i po prawej, przycisk produktu w przeglądzie zdjęć jest w etykiecie, test miejsc w API stoi obok tabeli, powtórzone znakowanie ma czerwoną ramkę, logo w menu ma proste rogi, maszyna na stronie głównej rzuca cień, a przyciski admina na stronie są na wierzchu.',
      },
    ],
  },
  {
    version: '1.27.0',
    date: '2026-10-03',
    title: 'Przegląd zdjęć jako edytor',
    synopsis: 'w przeglądzie zdjęć z API można zarządzać wszystkimi zdjęciami produktu.',
    changes: [
      {
        label: 'Przegląd zdjęć z API',
        text: 'pokazuje wszystkie zdjęcia produktu, a nie tylko warianty z nowymi.',
        big: true,
      },
      'Zdjęcia, które już były, można usuwać i przenosić między galerią a wariantami, tak jak nowe.',
      'Obok strzałki w rogu zdjęcia jest kosz, a po kliknięciu przycisk cofnięcia; kliknięcie samego zdjęcia działa tak samo.',
      'Po skanie każde nowe zdjęcie ma znak NOWE i fioletową ramkę; przy imporcie tylko u produktów, które już są w bazie.',
      {
        label: 'Drobne zmiany',
        text: 'licznik zdjęć do usunięcia na pasku przeglądu, nazwa i kod produktu na szarym tle, dwa paski w API › Produkty połączone w jeden, a Skanuj i Importuj są równej szerokości.',
      },
    ],
  },
  {
    version: '1.26.0',
    date: '2026-10-03',
    title: 'Szybsze skanowanie i lupa',
    synopsis: 'krótsze skany i przeliczanie cen, podgląd zdjęć w pełnym rozmiarze, trzy kolumny w edytorze.',
    changes: [
      { label: 'Skanowanie', text: 'skany są kilka razy szybsze, najbardziej te duże, jak AXPOL.', big: true },
      'Przeliczanie cen zostało usprawnione i trwa krócej.',
      'Skan dostawcy, który przestał odpowiadać, nie wisi już bez końca: kończy się komunikatem z jego nazwą.',
      'Drugiego skanu tej samej firmy nie da się zacząć, dopóki trwa pierwszy.',
      { label: 'Poprawka', text: 'duże skany nie przerywają się już z braku pamięci na serwerze.' },
      {
        label: 'Lupa',
        text: 'każde zdjęcie w panelu ma w rogu lupę, która otwiera je w pełnym rozmiarze; to samo robi prawy przycisk myszy.',
        big: true,
      },
      'Przegląd zdjęć z API oznacza NOWE tylko przy produktach, które mają też wcześniejsze zdjęcia, a w tytule ma nazwę i kod.',
      { label: 'Edytor', text: 'ma najwyżej trzy kolumny, a lewa kolumna cennika jest szeroka jak karta wariantu.' },
      {
        label: 'Drobne zmiany',
        text: 'puste warianty znikają przy zapisie, pole Widok pokazuje obok nazwy ilości widoku, wartości marż odgórnych widać obok nich, na niebiesko, gdy są w użyciu, Wyloguj, imię i wersja są na środku menu, kafelki galerii i załączników wypełniają cały wiersz, „Dodaj” w wariantach i kalkulacjach jest wąski jak w galerii (obok karty: bokiem), uchwyt i strzałka na zdjęciach w przeglądzie pojawiają się jak lupa, linia między grupami zdjęć jest wyraźniejsza, a zdjęcie używane też w innym produkcie zachowuje swoją nazwę.',
      },
      { label: 'P.S.', text: 'Dziękuję za prezent!!! ❤️ Superancki jest :))', big: true },
    ],
  },
  {
    version: '1.25.0',
    date: '2026-10-03',
    title: 'Zdjęcia, API i strona produktu',
    synopsis: 'przeciąganie zdjęć, przegląd zdjęć z API i nowe znaczniki na stronie.',
    changes: [
      {
        label: 'Przeciąganie',
        text: 'zdjęcia i załączniki przestawia się, przeciągając je za uchwyt w rogu; Esc anuluje.',
        big: true,
      },
      'Przycisk ze strzałką w rogu zdjęcia przenosi je między galerią a wariantami.',
      {
        label: 'Kolejność',
        text: 'warianty i znakowania układają się same przy zapisie, więc strzałek już nie ma.',
        big: true,
      },
      'Niebieska ramka oznacza zdjęcie z kafelka na stronie, a przerywana zdjęcie po najechaniu.',
      'W wyborze znakowania nieaktywne są te dodawane przez skaner i te, które produkt już ma.',
      {
        label: 'Przegląd zdjęć z API',
        text: 'nowe zdjęcia widać obok obecnych, w kolejności dostawcy i ze znakiem NOWE.',
        big: true,
      },
      'Import produktów pyta o zgodę dopiero po przejrzeniu zdjęć i ma Anuluj zamiast „Później”.',
      {
        label: 'API',
        text: 'przyciski nad listą przenoszą na górę wycofane, nowe warianty, komplikacje lub zaimportowane.',
      },
      'Fioletowa chmurka oznacza nowe warianty u dostawcy, a kolumna Stan nazywa się teraz Komplikacje.',
      { label: 'Poprawka', text: 'wyłączenie i ponowne włączenie znakowania nie wymaga już zapisu produktu.' },
      { label: 'Poprawka', text: 'materiały z PAR i MidOcean nie powtarzają się po następnym skanie.' },
      { label: 'Strona', text: 'produkt bez cen pokazuje „Zapytaj o cenę”, także na karcie PDF.', big: true },
      'Znaczniki mają nowe kolory, „Brak” to „Koniec nakładu”, a produkt bez towaru dostaje „Chwilowy brak”.',
      {
        label: 'Drobne zmiany',
        text: 'puste kafelki znikają przy zapisie, cenniki mieszczą się w wierszu, okna wyglądają jednakowo, a zdjęcie usunięte u dostawcy znika z całego produktu. Zdjęcia wariantów są zawsze w galerii strony (pole „Galeria” zniknęło), która pokazuje dwa rzędy miniatur, a resztę pod „+N”.',
      },
    ],
  },
  {
    version: '1.24.1',
    date: '2026-10-02',
    title: 'Poprawki',
    synopsis: 'błąd przy otwieraniu produktu, data wersji w menu.',
    changes: [
      {
        label: 'Poprawka',
        text: 'otwarcie produktu nie pokazuje już błędu „Cannot read properties of null”; zapis działał mimo niego.',
      },
      'Obok wersji na dole menu widać datę jej wydania.',
      'W przeglądarce, w której historii zmian jeszcze nie otwierano, nowe są wersje z ostatniego tygodnia.',
    ],
  },
  {
    version: '1.24.0',
    date: '2026-10-02',
    title: 'Produkty, Zapytania i API',
    synopsis: 'miniatury, filtry, załączniki, stan produktów z API i historia zmian.',
    changes: [
      {
        label: 'Miniatury',
        text: 'listy produktów i API mają miniatury; najechanie powiększa zdjęcie, a kliknięcie otwiera oryginał.',
        big: true,
      },
      {
        label: 'Filtry',
        text: 'w filtrach Producent i Kolor można zaznaczyć kilka wartości naraz; „Brak” pokazuje produkty bez nich.',
        big: true,
      },
      {
        label: 'Załączniki',
        text: 'na końcu edytora produktu dodaje się pliki (np. instrukcję), które klienci pobiorą z karty produktu.',
        big: true,
      },
      'Nowe rodzaje kolorów: Drewno i Neutralny, z własnymi wzorami zamiast jednolitego koloru.',
      'Zdjęć nie da się już ukryć: zdjęcie, które nie ma się pokazywać, usuwa się z produktu (plik zostaje w Bibliotece).',
      { label: 'Poprawka', text: 'wyjście z edytora produktu do innego edytora nie zawiesza strony.' },
      {
        label: 'Zapytania',
        text: 'zapytanie wysłane z karty produktu ma przycisk, który otwiera ten produkt w nowej karcie.',
        big: true,
      },
      {
        label: 'Stan',
        text: 'ikona w nowej kolumnie API ostrzega, czego produktowi zabraknie po imporcie, np. znakowań albo kategorii.',
        big: true,
      },
      {
        label: 'Reguły do przejrzenia',
        text: 'w zakładkach Kategorie, Znakowania i Miejsca są gotowe reguły dla dostawców; sprawdź je, zanim zeskanujesz dostawcę.',
        big: true,
      },
      {
        label: 'Uwaga',
        text: 'każdy skan, także ten po stany, stosuje te reguły do znakowań i cen produktów.',
        big: true,
      },
      'Reguła miejsc, bez której wynik byłby taki sam, jest oznaczona jako zbędna i można ją usunąć.',
      'Reklama zewnętrzna ma rysunki zamiast zdjęć, a w ofercie jest Roll-up.',
      { label: 'Historia zmian', text: 'kliknij wersję na dole menu, żeby zobaczyć, co się zmieniło.', big: true },
    ],
  },
  {
    version: '1.23.1',
    date: '2026-09-29',
    title: 'Ikona',
    synopsis: 'Nowości.',
    changes: ['Ikona działu Nowości w menu strony jest przerysowana.'],
  },
  {
    version: '1.23.0',
    date: '2026-09-29',
    title: 'Tabele i strona',
    synopsis: 'logo producentów, wybór kolumn, węższa kolumna treści.',
    changes: [
      'Przy nazwach producentów w całym panelu widać ich logo, więc łatwiej ich rozróżnić.',
      {
        label: 'Kolumny',
        text: 'w ostatniej kolumnie tabeli wybiera się, które kolumny widać; wybór pamięta tylko ta przeglądarka.',
        big: true,
      },
      'Filtr kategorii na liście produktów obejmuje też jej podkategorie.',
      {
        label: 'Strona',
        text: 'treść wszystkich podstron ma jedną szerokość, a nagłówek strony głównej jest granatowy.',
      },
    ],
  },
  {
    version: '1.22.0',
    date: '2026-09-28',
    title: 'Skanowanie i panel',
    synopsis: 'pełna synchronizacja z dostawcami, oznaczenia produktów i nieprzeczytane zapytania.',
    changes: [
      { label: 'HappyBrands', text: 'nowy dostawca w API, skanowany i importowany jak pozostali.', big: true },
      {
        label: 'Pełny skan',
        text: 'skan aktualizuje nie tylko ceny i stany, ale też opisy, materiały, rozmiary, znakowania i kategorie.',
        big: true,
      },
      'Strona API ma zakładki: Produkty, Kategorie, Znakowania i Miejsca.',
      'Gdy skan chce ukryć albo wyzerować dużo naraz (np. awaria API dostawcy), najpierw pyta, czy zapisać.',
      {
        label: 'Mapowania',
        text: 'w zakładkach API każdej kategorii, znakowaniu i miejscu dostawcy przypisuje się nasz odpowiednik.',
        big: true,
      },
      'Kategoria wskazana regułą znika ze skanowanych produktów, których kategorie dostawcy do niej nie prowadzą.',
      'Pola ustawiane przez skaner mają w edytorze znaczek API i są zablokowane, bo ręczna zmiana i tak zostałaby nadpisana.',
      {
        label: 'Nowe zdjęcia',
        text: 'nowe zdjęcia od dostawcy czekają po skanie na akceptację; odrzucone nie wracają przy kolejnych skanach.',
        big: true,
      },
      {
        label: 'Posprzątaj',
        text: 'przycisk w Bibliotece pokazuje pliki, których nic nie używa, i usuwa zaznaczone.',
        big: true,
      },
      'Edytor pliku pokazuje, gdzie plik jest używany; używanego pliku nie da się usunąć.',
      {
        label: 'Oznaczenia',
        text: 'Nowości, Bestsellery i Promocje zaznacza się w produkcie; działy na stronie tworzą się z tych zaznaczeń same.',
        big: true,
      },
      {
        label: 'Duplikuj',
        text: 'przycisk w edytorze tworzy ukrytą kopię produktu jako produkt REED, z „(2)” w kodzie i nazwie.',
        big: true,
      },
      'Listę produktów można filtrować po oznaczeniach (Widoczny, Nowość, Promocja…).',
      'Kalkulacje mają dwie zakładki: Znakowania oraz Marże i widoki.',
      {
        label: 'Nieprzeczytane',
        text: 'nowe zapytania są pomarańczowe, a menu pokazuje ich liczbę; otwarcie oznacza zapytanie jako przeczytane.',
        big: true,
      },
      '„Informacje handlowe” nazywają się teraz „Paragrafy”; działają tak samo jak wcześniej.',
      { label: 'Karta produktu', text: 'zdjęcia otwierają się na cały ekran, a kartę produktu można pobrać w PDF.' },
    ],
  },
  {
    version: '1.21.0',
    date: '2026-09-24',
    title: 'Nowa strona na reed.kalisz.pl',
    synopsis: 'ostatnie szlify.',
    changes: [
      {
        label: 'Nowa strona',
        text: 'nowy wygląd, dotąd tylko na wersji testowej, trafia na reed.kalisz.pl.',
        big: true,
      },
      'Nowości, Bestsellery i Promocje mają w menu własne rysunki.',
      'Formularz zapytania ma nowy wygląd i większe pole zgody na przetwarzanie danych.',
    ],
  },
  {
    version: '1.20.1',
    date: '2026-09-24',
    title: 'Strona główna',
    synopsis: 'nieznane bloki.',
    changes: [{ label: 'Poprawka', text: 'blok, którego strona jeszcze nie zna, nie psuje strony głównej.' }],
  },
  {
    version: '1.20.0',
    date: '2026-09-24',
    title: 'Edytor strony głównej',
    synopsis: 'stałe bloki.',
    changes: [
      'Siatka działów i sekcja o Kaliszu są widoczne w edytorze strony głównej; własne bloki dodaje się przed nimi i po nich.',
    ],
  },
  {
    version: '1.19.3',
    date: '2026-09-24',
    title: 'Czcionki',
    synopsis: 'zapamiętane.',
    changes: ['Przeglądarka pobiera czcionki strony tylko raz, więc kolejne wizyty są szybsze.'],
  },
  {
    version: '1.19.2',
    date: '2026-09-24',
    title: 'Pamięć podręczna',
    synopsis: 'zmiany z opóźnieniem.',
    changes: [
      {
        label: 'Uwaga',
        text: 'zmiana zapisana w panelu pojawia się na stronie nawet minutę później; to nie błąd, wystarczy odświeżyć.',
        big: true,
      },
    ],
  },
  {
    version: '1.19.1',
    date: '2026-09-24',
    title: 'Działy',
    synopsis: 'szybsze liczenie.',
    changes: ['Liczby produktów w działach strony głównej liczą się szybciej.'],
  },
  {
    version: '1.19.0',
    date: '2026-09-24',
    title: 'Ukryte produkty',
    synopsis: 'podgląd dla administratorów.',
    changes: [
      {
        label: 'Ukryte produkty',
        text: 'zalogowany administrator otworzy ukryty produkt z linku, np. żeby go sprawdzić; klienci dostają 404.',
        big: true,
      },
      'Strony przygotowują się na serwerze, więc wczytują się szybciej.',
    ],
  },
  {
    version: '1.18.0',
    date: '2026-09-24',
    title: 'Szybciej',
    synopsis: 'strona główna i ceny.',
    changes: [
      'Strona główna wczytuje się szybciej, a kolejne produkty w paskach są gotowe z wyprzedzeniem.',
      'Cały kafelek produktu jest klikalny, a po najechaniu pokazuje drugie zdjęcie.',
      'Cena na kafelku i karcie ma dopisek „ze znakowaniem”.',
    ],
  },
  {
    version: '1.17.0',
    date: '2026-09-23',
    title: 'Działy',
    synopsis: 'ikony i liczby.',
    changes: [
      'Każdy dział na stronie głównej ma ikonę i liczbę produktów.',
      'Tekst na banerach ma rozmyte tło, więc czyta się go na każdym zdjęciu.',
    ],
  },
  {
    version: '1.16.6',
    date: '2026-09-23',
    title: 'Strona główna',
    synopsis: 'szybciej.',
    changes: ['Strona główna wczytuje się szybciej, bo podsumowanie katalogu liczy serwer.'],
  },
  {
    version: '1.16.5',
    date: '2026-09-23',
    title: 'Formularz',
    synopsis: 'nowe teksty.',
    changes: ['Formularz na karcie produktu nazywa się „Zapytanie” i ma nowe podpowiedzi.'],
  },
  {
    version: '1.16.4',
    date: '2026-09-23',
    title: 'Kategorie',
    synopsis: 'układ.',
    changes: ['Poprawiony układ strony kategorii: nagłówek, sortowanie i lista produktów.'],
  },
  {
    version: '1.16.3',
    date: '2026-09-23',
    title: 'Beta',
    synopsis: 'bez hasła.',
    changes: ['Wersja testowa strony chwilowo nie wymaga hasła, żeby łatwiej ją było sprawdzać.'],
  },
  {
    version: '1.16.2',
    date: '2026-09-23',
    title: 'Sesja',
    synopsis: 'bez błędu.',
    changes: [{ label: 'Poprawka', text: 'wygaśnięcie logowania nie kończy się błędem strony, tylko wylogowaniem.' }],
  },
  {
    version: '1.16.1',
    date: '2026-09-23',
    title: 'Edytor strony głównej',
    synopsis: 'bez fałszywych alarmów.',
    changes: [
      { label: 'Poprawka', text: 'edytor strony głównej nie zgłasza niezapisanych zmian, gdy nic nie zmieniono.' },
    ],
  },
  {
    version: '1.16.0',
    date: '2026-09-23',
    title: 'Nowa strona',
    synopsis: 'wygląd, telefony i każda podstrona od nowa.',
    changes: [
      { label: 'Nowy wygląd', text: 'cała strona dostała nową czcionkę, kolory i układ.', big: true },
      {
        label: 'Telefony',
        text: 'strona wygodnie działa na telefonach i tabletach, z menu otwieranym na cały ekran.',
        big: true,
      },
      'Menu kategorii, wyszukiwarka i kontakt są w stałym panelu po lewej.',
      { label: 'Strona główna', text: 'nowy nagłówek, siatka działów katalogu i sekcja o siedzibie w Kaliszu.' },
      {
        label: 'Kategorie',
        text: 'produkty można sortować, a nowe kafelki pokazują oznaczenia, np. Nowość czy Promocja.',
      },
      { label: 'Karta produktu', text: 'nowy układ, w którym cena i przycisk zapytania są zawsze na widoku.' },
      { label: 'Kontakt', text: 'nowa strona z formularzem zapytania, danymi firmy i mapą dojazdu.' },
      'Strona jest lepiej opisana dla Google, więc łatwiej ją znaleźć.',
    ],
  },
  {
    version: '1.15.1',
    date: '2026-09-23',
    title: 'Beta',
    synopsis: 'wersja testowa.',
    changes: [
      'Wersja testowa strony buduje się z osobnej wersji kodu, więc można ją zmieniać bez ruszania właściwej strony.',
    ],
  },
  {
    version: '1.15.0',
    date: '2026-09-22',
    title: 'Ukryte',
    synopsis: 'znikają z list.',
    changes: [
      'Ukryte produkty, warianty i kategorie nie pokazują się na stronie, także zalogowanym.',
      'Zalogowany administrator widzi przy znakowaniu na stronie, czyje to znakowanie.',
    ],
  },
  {
    version: '1.14.1',
    date: '2026-09-22',
    title: 'Porządki',
    synopsis: 'jednorazowy skrypt.',
    changes: ['Usunięty skrypt, który już zrobił swoje; nic się nie zmienia.'],
  },
  {
    version: '1.14.0',
    date: '2026-09-22',
    title: 'BlueCollection',
    synopsis: 'znakowania i nowy panel reguł.',
    changes: [
      { label: 'BlueCollection', text: 'importowane produkty dostają znakowania same, tak jak MidOcean.', big: true },
      {
        label: 'Reguły znakowań',
        text: 'kody dostawcy wybiera się z listy, a błędne lub zbędne reguły są oznaczone.',
        big: true,
      },
      'Nowa reguła „Ignoruj” dla kodów, których nigdy nie chcemy importować.',
      'Kod bez reguły używa naszego znakowania tego dostawcy o tym samym kodzie, a gdy takiego nie ma, nie importuje się.',
    ],
  },
  {
    version: '1.13.6',
    date: '2026-09-22',
    title: 'Kody',
    synopsis: 'AXPOL i USBSystem.',
    changes: [
      { label: 'Poprawka', text: 'produkty AXPOL z kropką w kodzie (np. P322.08) nie sklejają się w jeden produkt.' },
      'Kody produktów USBSystem nie zmieniają się, gdy dostawca przestawi ofertę.',
    ],
  },
  {
    version: '1.13.5',
    date: '2026-09-22',
    title: 'API',
    synopsis: 'zawsze najnowszy skan.',
    changes: [
      {
        label: 'Poprawka',
        text: 'po nowym skanie lista API nie pokazuje starego skanu zapamiętanego przez przeglądarkę.',
      },
    ],
  },
  {
    version: '1.13.4',
    date: '2026-09-21',
    title: 'Skanowanie',
    synopsis: 'jedna linijka zmian. Ostrzeżenie leży teraz równo.',
    changes: ['Ostrzeżenie widoczne podczas skanu jest poprawnie ułożone nad paskiem postępu.'],
  },
  {
    version: '1.13.3',
    date: '2026-09-21',
    title: 'Skanowanie',
    synopsis: 'ostrzeżenie.',
    changes: [
      'Ostrzeżenie „Nie zamykaj przeglądarki” jest widoczne przez cały skan, a przycisk „Skanuj” jest wtedy nieaktywny.',
    ],
  },
  {
    version: '1.13.2',
    date: '2026-09-21',
    title: 'Skanowanie',
    synopsis: 'bezpieczniej.',
    changes: [
      {
        label: 'Poprawka',
        text: 'wynik skanu zapisuje się tylko u dostawcy, którego skanowano, nawet gdy w trakcie zmienisz wybór.',
      },
      'Gdy skan się nie uda, panel pokazuje komunikat z przyczyną, zamiast odświeżać stronę.',
      'Produkty „Gotowy” wracają po skanie także wtedy, gdy ich cena się nie zmieniła.',
    ],
  },
  {
    version: '1.13.1',
    date: '2026-08-28',
    title: '„Ryczałt”',
    synopsis: 'widoczny.',
    changes: [{ label: 'Poprawka', text: 'napis „Ryczałt” w tabeli znakowań nie chowa się pod innymi elementami.' }],
  },
  {
    version: '1.13.0',
    date: '2026-08-26',
    title: 'DOSTĘPNY',
    synopsis: 'nowy stan magazynowy.',
    changes: [
      {
        label: 'Dostępny',
        text: 'w wariancie zaznacza się „Dostępny”, gdy nie znamy liczby sztuk; strona pokazuje wtedy „DOSTĘPNY”.',
        big: true,
      },
      'Wariant, który zniknął z oferty dostawcy, traci „Dostępny” i spada do zera przy skanie.',
      'Stan na stronie to zawsze liczba sztuk, DOSTĘPNY, ZAPYTAJ albo BRAK.',
    ],
  },
  {
    version: '1.12.14',
    date: '2026-08-25',
    title: 'Biblioteka',
    synopsis: 'pliki z tagami.',
    changes: ['Biblioteka ukrywa wszystkie pliki z tagami (to pliki techniczne).'],
  },
  {
    version: '1.12.13',
    date: '2026-08-25',
    title: 'Biblioteka',
    synopsis: 'bez plików technicznych.',
    changes: [
      'Biblioteka nie pokazuje plików technicznych, których nie trzeba oglądać.',
      'Z menu zniknął przycisk „Notyfikacje”, który niczego nie robił.',
    ],
  },
  {
    version: '1.12.12',
    date: '2026-08-21',
    title: 'Porządki',
    synopsis: 'ustawienia kopii.',
    changes: ['Porządki w ustawieniach kopii; nic się nie zmienia.'],
  },
  {
    version: '1.12.11',
    date: '2026-08-21',
    title: 'Kopie',
    synopsis: 'lokalne.',
    changes: ['Kopie zapasowe z ostatnich 14 dni są też na samym serwerze.'],
  },
  {
    version: '1.12.10',
    date: '2026-08-21',
    title: 'Przeprowadzka',
    synopsis: 'reed.kalisz.pl na nowym serwerze. Nikt nie zauważył i o to chodziło.',
    changes: ['Strona i panel działają z nowego, szybszego serwera.'],
  },
  {
    version: '1.12.9',
    date: '2026-08-21',
    title: 'Kopie poza serwerem',
    synopsis: 'i wersja testowa.',
    changes: [
      {
        label: 'Kopie zapasowe',
        text: 'baza i pliki codziennie trafiają, zaszyfrowane, na osobny serwer; najstarsze kopie mają pół roku.',
        big: true,
      },
      'Wersja testowa strony pod beta.reed.kalisz.pl, do sprawdzania zmian przed publikacją.',
    ],
  },
  {
    version: '1.12.8',
    date: '2026-08-20',
    title: 'Nowy serwer',
    synopsis: 'przygotowania.',
    changes: ['Przygotowania do przeniesienia strony na nowy serwer; na razie nic się nie zmienia.'],
  },
  {
    version: '1.12.7',
    date: '2026-07-28',
    title: 'Poprawka',
    synopsis: 'odświeżanie po przeliczeniu.',
    changes: [{ label: 'Poprawka', text: 'po przeliczeniu cen produkty odświeżają się w panelu.' }],
  },
  {
    version: '1.12.6',
    date: '2026-06-16',
    title: 'Kopie zapasowe',
    synopsis: 'działają same.',
    changes: [{ label: 'Poprawka', text: 'nocne kopie zapasowe i sprzątanie uruchamiają się same.' }],
  },
  {
    version: '1.12.5',
    date: '2026-06-16',
    title: 'Porządki',
    synopsis: 'plik konfiguracyjny.',
    changes: ['Usunięty nieużywany plik; nic się nie zmienia.'],
  },
  {
    version: '1.12.4',
    date: '2026-06-16',
    title: 'Kopie zapasowe',
    synopsis: 'i nocne sprzątanie.',
    changes: [
      'Przed każdym nocnym sprzątaniem robi się kopia zapasowa bazy.',
      'Co noc baza usuwa starą historię zmian, żeby nie puchła.',
    ],
  },
  {
    version: '1.12.3',
    date: '2026-05-09',
    title: 'Filtry',
    synopsis: 'mniejsze.',
    changes: ['Przyciski filtrów są mniejsze i zajmują mniej miejsca.'],
  },
  {
    version: '1.12.2',
    date: '2026-05-09',
    title: 'Przeliczanie',
    synopsis: 'partiami.',
    changes: ['Przeliczanie cen wszystkich produktów idzie partiami, więc mniej obciąża serwer.'],
  },
  {
    version: '1.12.1',
    date: '2026-05-09',
    title: 'Porządki',
    synopsis: 'ładniej ułożony kod. Widać to tylko od środka.',
    changes: ['Porządki w kodzie; nic się nie zmienia.'],
  },
  {
    version: '1.12.0',
    date: '2026-05-09',
    title: 'USBSystem',
    synopsis: 'nowy dostawca.',
    changes: [
      {
        label: 'USBSystem',
        text: 'nowy dostawca pamięci USB, którego produkty skanuje się i importuje jak pozostałe.',
        big: true,
      },
      'Długie kody w tabeli API są skracane, a całe widać po najechaniu.',
    ],
  },
  {
    version: '1.11.5',
    date: '2026-03-19',
    title: 'AXPOL',
    synopsis: 'przeprowadzili się z .com.pl na .com. Poszliśmy za nimi.',
    changes: [
      { label: 'Poprawka', text: 'skan AXPOL działa pod ich nowym adresem.' },
      'Podczas skanowania widać licznik postępu, więc wiadomo, ile jeszcze zostało.',
    ],
  },
  {
    version: '1.11.4',
    date: '2026-03-15',
    title: 'Kalkulacje',
    synopsis: 'przelicza tylko, gdy trzeba.',
    changes: [
      'Zmiana w znakowaniu, która nie wpływa na cenę (np. nazwy), zapisuje się od razu, bez przeliczania produktów.',
      'Nakłady w tabeli są zawsze ułożone rosnąco.',
    ],
  },
  {
    version: '1.11.3',
    date: '2026-03-13',
    title: 'Promotionway',
    synopsis: 'ceny od nakładu.',
    changes: [
      'Produkty Promotionway z ceną zależną od nakładu są oznaczone jako niekompatybilne, żeby nie trafiły do bazy ze złą ceną.',
    ],
  },
  {
    version: '1.11.2',
    date: '2026-03-13',
    title: 'Poprawka',
    synopsis: 'skan bez „Gotowych”.',
    changes: [
      { label: 'Poprawka', text: 'skan dostawcy, który nie ma żadnego produktu „Gotowy”, nie kończy się błędem.' },
    ],
  },
  {
    version: '1.11.1',
    date: '2026-03-13',
    title: 'Dostawcy',
    synopsis: 'znowu zmienili API bez uprzedzenia. Już nas to nie dziwi.',
    changes: [
      { label: 'Poprawka', text: 'skan EasyGifts i Macma działa z nową wersją ich API.' },
      'Stan magazynowy EasyGifts, Macma i Promotionway to suma ich kilku magazynów.',
    ],
  },
  {
    version: '1.11.0',
    date: '2026-01-30',
    title: '„Do edycji”',
    synopsis: 'nowy status w API.',
    changes: ['Produkt na liście API można oznaczyć statusem „✏️ Do edycji”, żeby wrócić do niego później.'],
  },
  {
    version: '1.10.0',
    date: '2026-01-22',
    title: 'Biblioteka',
    synopsis: 'wyszukiwarka.',
    changes: ['Pliki w bibliotece wyszukuje się po nazwie lub tytule, także w oknie wyboru zdjęcia.'],
  },
  {
    version: '1.9.0',
    date: '2025-12-02',
    title: 'PAR',
    synopsis: 'cena najdroższego wariantu.',
    changes: ['Cena produktu PAR to cena jego najdroższego wariantu, a nie przypadkowego pierwszego.'],
  },
  {
    version: '1.8.2',
    date: '2025-11-28',
    title: 'Porządki',
    synopsis: 'i narzędzia techniczne.',
    changes: ['Ukryta strona z narzędziami technicznymi, np. do przeliczenia cen wszystkich produktów naraz.'],
  },
  {
    version: '1.8.1',
    date: '2025-11-15',
    title: 'EasyGifts',
    synopsis: 'zmiana w API.',
    changes: ['Ceny i stany EasyGifts przypisują się do konkretnych wariantów, po zmianie w ich API.'],
  },
  {
    version: '1.8.0',
    date: '2025-11-14',
    title: '„Gotowy”',
    synopsis: 'produkty wracają po skanie.',
    changes: [
      'Wyłączony produkt ze statusem „✅ Gotowy” włącza się sam po skanie, gdy wróci do oferty dostawcy; inne statusy zostają wyłączone.',
    ],
  },
  {
    version: '1.7.0',
    date: '2025-09-28',
    title: 'Opis kategorii',
    synopsis: 'na stronie.',
    changes: [
      'Opis wpisany w edytorze kategorii pokazuje się na stronie nad jej produktami, z pogrubieniami i listami.',
    ],
  },
  {
    version: '1.6.11',
    date: '2025-09-24',
    title: 'Testy',
    synopsis: 'szybszy zapis.',
    changes: ['Testy szybszego zapisywania; nic się nie zmienia.'],
  },
  {
    version: '1.6.10',
    date: '2025-08-29',
    title: 'Kalkulacje',
    synopsis: 'zapisywanie znowu zapisuje, i to szybciej.',
    changes: [
      { label: 'Poprawka', text: 'zapis zmian w Kalkulacjach znów działa.' },
      'Zapis jest szybszy i pokazuje listę pozycji, które jeszcze czekają.',
    ],
  },
  {
    version: '1.6.9',
    date: '2025-08-22',
    title: 'Kalkulacje',
    synopsis: 'dodawanie znakowań.',
    changes: [
      { label: 'Poprawka', text: 'dodawanie nowych znakowań w Kalkulacjach znów działa.' },
      { label: 'Poprawka', text: 'po zmianie znakowania ceny produktów liczą się z nowych wartości, a nie starych.' },
    ],
  },
  {
    version: '1.6.8',
    date: '2025-08-17',
    title: 'Reguły znakowań',
    synopsis: 'zwarty wygląd.',
    changes: ['Sekcja reguł znakowań jest w ramce i zajmuje mniej miejsca.'],
  },
  {
    version: '1.6.7',
    date: '2025-08-17',
    title: 'Reguły znakowań',
    synopsis: 'poprawki.',
    changes: [{ label: 'Poprawka', text: 'po przełączeniu dostawcy nie widać już reguł poprzedniego.' }],
  },
  {
    version: '1.6.6',
    date: '2025-06-30',
    title: 'AXPOL',
    synopsis: 'poprzednia poprawka pobierała część oferty. Ta pobiera całą.',
    changes: [{ label: 'Poprawka', text: 'skan AXPOL znów pobiera całą ofertę, a nie pierwsze 1000 produktów.' }],
  },
  {
    version: '1.6.5',
    date: '2025-06-29',
    title: 'AXPOL',
    synopsis: 'ich certyfikat, nasza poprawka.',
    changes: [
      { label: 'Poprawka', text: 'skan i zdjęcia AXPOL działają, mimo problemu z certyfikatem po stronie AXPOL.' },
    ],
  },
  {
    version: '1.6.4',
    date: '2025-06-29',
    title: 'Reguły',
    synopsis: 'czerwone kosze.',
    changes: ['Przyciski usuwania reguł są czerwone, żeby nie kliknąć ich przypadkiem.'],
  },
  {
    version: '1.6.3',
    date: '2025-06-29',
    title: 'Menu kategorii',
    synopsis: 'równe wcięcia.',
    changes: ['Podkategorie w menu strony mają równe wcięcia i linię, zamiast coraz większych odstępów.'],
  },
  {
    version: '1.6.2',
    date: '2025-06-27',
    title: 'Poprawka',
    synopsis: 'skaner.',
    changes: [{ label: 'Poprawka', text: 'panel znów łączy się ze skanerem API.' }],
  },
  {
    version: '1.6.1',
    date: '2025-06-27',
    title: 'Poprawka',
    synopsis: 'import z API znowu działa. Nie działał przez pół godziny.',
    changes: [{ label: 'Poprawka', text: 'dodawanie nowych produktów z API znów działa.' }],
  },
  {
    version: '1.6.0',
    date: '2025-06-27',
    title: 'Reguły znakowań',
    synopsis: 'ustawiane w panelu.',
    changes: [
      {
        label: 'Reguły znakowań',
        text: 'w API ustala się, które nasze znakowanie dostaje kod znakowania dostawcy.',
        big: true,
      },
      'Reguła może też wybierać znakowanie według ceny produktu albo powierzchni nadruku.',
      'Produkty z MidOcean liczą się z marżą na całość zamiast marży produktu.',
    ],
  },
  {
    version: '1.5.1',
    date: '2025-06-26',
    title: 'Reguły znakowań',
    synopsis: 'początek edytora.',
    changes: ['Strona API nie ma już ostrzeżenia „BETA” u góry.'],
  },
  {
    version: '1.5.0',
    date: '2025-06-25',
    title: 'Znakowania z API',
    synopsis: 'MidOcean.',
    changes: [
      {
        label: 'Znakowania z API',
        text: 'produkty importowane z MidOcean dostają znakowania same, według technik nadruku podanych przez dostawcę.',
        big: true,
      },
      'Znakowanie może zależeć od ceny produktu albo od powierzchni nadruku.',
    ],
  },
  {
    version: '1.4.5',
    date: '2025-06-24',
    title: 'Znakowania z API',
    synopsis: 'dalsze prace.',
    changes: ['Dalsze prace nad znakowaniami z API; na razie nic nie widać.'],
  },
  {
    version: '1.4.4',
    date: '2025-06-24',
    title: 'Znakowania z API',
    synopsis: 'początek prac.',
    changes: ['Początek prac nad tym, żeby produkty z API dostawały znakowania same; na razie nic nie widać.'],
  },
  {
    version: '1.4.3',
    date: '2025-06-24',
    title: 'Poprawka',
    synopsis: 'obrazki w kafelkach.',
    changes: [{ label: 'Poprawka', text: 'obrazki wybrane z biblioteki wyświetlają się w kafelkach strony głównej.' }],
  },
  {
    version: '1.4.2',
    date: '2025-06-18',
    title: 'Tabela znakowań',
    synopsis: 'przypięty nagłówek.',
    changes: ['Nagłówek tabeli znakowań i jej pierwsze kolumny zostają na miejscu przy przewijaniu.'],
  },
  {
    version: '1.4.1',
    date: '2025-06-18',
    title: 'Porządki',
    synopsis: 'konfiguracja.',
    changes: ['Porządki w plikach konfiguracyjnych; nic się nie zmienia.'],
  },
  {
    version: '1.4.0',
    date: '2025-06-18',
    title: 'Kalkulacje',
    synopsis: 'karta dla każdego dostawcy.',
    changes: [
      'Kalkulacje mają osobną kartę dla każdego dostawcy, zamiast jednej długiej strony.',
      'Kolejność znakowań ustawia się, wpisując numer pozycji, zamiast klikać strzałki.',
      'Nakłady dodaje się, zmienia i usuwa prosto w tabeli znakowań.',
    ],
  },
  {
    version: '1.3.6',
    date: '2025-06-11',
    title: 'Konfiguracja',
    synopsis: 'adresy serwerów.',
    changes: ['Zmiana techniczna, dzięki której można uruchomić wersję testową strony; nic nie widać.'],
  },
  {
    version: '1.3.5',
    date: '2025-06-11',
    title: 'Poprawka',
    synopsis: 'kafelki strony głównej.',
    changes: [{ label: 'Poprawka', text: 'zdjęcia w kafelkach strony głównej znów się wyświetlają.' }],
  },
  {
    version: '1.3.4',
    date: '2025-06-09',
    title: 'Dokumentacja',
    synopsis: 'czwarta poprawka dokumentacji z rzędu. Strona dalej ta sama.',
    changes: ['Zmiany tylko w dokumentacji technicznej; strona i panel bez zmian.'],
  },
  {
    version: '1.3.3',
    date: '2025-06-08',
    title: 'Dokumentacja',
    synopsis: 'zrzuty ekranu.',
    changes: ['Zmiany tylko w dokumentacji technicznej; strona i panel bez zmian.'],
  },
  {
    version: '1.3.2',
    date: '2025-06-06',
    title: 'Dokumentacja',
    synopsis: 'tytuł.',
    changes: ['Zmiany tylko w dokumentacji technicznej; strona i panel bez zmian.'],
  },
  {
    version: '1.3.1',
    date: '2025-06-06',
    title: 'Dokumentacja',
    synopsis: 'opis projektu.',
    changes: ['Zmiany tylko w dokumentacji technicznej; strona i panel bez zmian.'],
  },
  {
    version: '1.3.0',
    date: '2025-06-06',
    title: 'reed.kalisz.pl i dostawcy',
    synopsis: 'dwa lata pracy w jednej wersji. Daty pojedynczych zmian zostały na starym serwerze.',
    changes: [
      { label: 'reed.kalisz.pl', text: 'nowa strona działa pod głównym adresem firmy.', big: true },
      {
        label: 'Edytor strony głównej',
        text: 'stronę główną układa się z bloków (tytuły, kafelki, kategorie) prosto na stronie.',
        big: true,
      },
      'Nowe oznaczenia produktów: Bestseller, Już wkrótce i Koniec nakładu.',
      'Karta produktu pokazuje ścieżkę kategorii i „Podobne produkty”.',
      'Formularz zapytania jest chroniony przed spamem, więc do Zapytań trafia mniej śmieci.',
      'Usuwając kategorię, wybiera się kategorię zastępczą, do której trafią jej produkty.',
      'Produkt ma pole „Notatki”, widoczne tylko w panelu.',
      'Plik w bibliotece można podmienić bez zmiany jego linku.',
      {
        label: 'API',
        text: 'siedmiu dostawców: PAR, MidOcean, BlueCollection, Macma, EasyGifts, Promotionway i AXPOL.',
        big: true,
      },
      {
        label: 'Skanowanie',
        text: 'skan sam aktualizuje ceny i stany magazynowe zaimportowanych produktów.',
        big: true,
      },
      'Produkty, które dostawca wycofał, wyłączają się same, a ich stan spada do zera.',
      'Rabat od dostawcy i jego koszty manipulacyjne ustawia się w panelu i wliczają się w ceny.',
    ],
  },
  {
    version: '1.2.1',
    date: '2023-04-14',
    title: 'Poprawki',
    synopsis: 'kategorie i pole znakowania.',
    changes: [
      { label: 'Poprawka', text: 'link do nieistniejącej kategorii pokazuje stronę 404.' },
      {
        label: 'Poprawka',
        text: 'wysokość pola znakowania na stronie pokazywała szerokość; teraz wymiary są poprawne.',
      },
    ],
  },
  {
    version: '1.2.0',
    date: '2023-03-27',
    title: '404 i ceny „od”',
    synopsis: 'porządki przed startem.',
    changes: [
      'Nieistniejący adres pokazuje stronę „Taka strona nie istnieje” zamiast błędu.',
      'Kafelki pokazują cenę „od”, a kategorie układają produkty od najtańszego.',
      'Filtr „Bez kategorii” na liście produktów pokazuje produkty, których nie ma w żadnej kategorii.',
    ],
  },
  {
    version: '1.1.0',
    date: '2023-03-16',
    title: 'Miejsce znakowania',
    synopsis: 'nowe pole.',
    changes: [
      'Produkt i każde jego znakowanie mają miejsce znakowania (np. „korpus”), widoczne na stronie.',
      { label: 'Poprawka', text: 'strona kategorii pokazuje wszystkie produkty, a nie tylko część.' },
    ],
  },
  {
    version: '1.0.1',
    date: '2023-03-12',
    title: 'API w produkcie',
    synopsis: 'prościej.',
    changes: ['Przełącznik API jest na górze edytora produktu, a kod produktu z API jest po prostu jego kodem.'],
  },
  {
    version: '1.0.0',
    date: '2023-03-09',
    title: 'Start',
    synopsis: 'pierwsza publiczna wersja strony.',
    changes: [
      { label: 'Nowa strona', text: 'nowy nagłówek i stopka oraz strony kategorii z menu bocznym.', big: true },
      'Nowe strony Kontakt, Polityka prywatności i Obowiązek informacyjny, wymagane na publicznej stronie.',
      'Zapytanie wysłane z karty produktu samo zawiera kod produktu.',
      'Menu górne, boczne i w stopce ustawia się w panelu osobno.',
    ],
  },
  {
    version: '0.22.3',
    date: '2023-02-23',
    title: 'Przeciąganie',
    synopsis: 'przed, za albo do środka.',
    changes: ['Przeciąganą kategorię albo pozycję menu można upuścić przed inną, za nią albo w niej.'],
  },
  {
    version: '0.22.2',
    date: '2023-02-16',
    title: 'Serwer',
    synopsis: 'new.reed.kalisz.pl.',
    changes: ['Strona i panel trafiają na prawdziwy serwer, pod adres new.reed.kalisz.pl.'],
  },
  {
    version: '0.22.1',
    date: '2023-02-14',
    title: 'Nagłówek',
    synopsis: 'przypięty.',
    changes: ['Nagłówek strony z menu i wyszukiwarką zostaje na górze przy przewijaniu.'],
  },
  {
    version: '0.22.0',
    date: '2023-01-28',
    title: 'API',
    synopsis: 'pierwszy skan dostawcy i informacje handlowe.',
    changes: [
      { label: 'Skanuj API', text: 'przycisk pobiera aktualną ofertę dostawcy PAR prosto do panelu.', big: true },
      {
        label: 'Import',
        text: 'produkty PAR dodaje się do bazy jednym kliknięciem, razem ze zdjęciami i kolorami.',
        big: true,
      },
      'Zaimportowane produkty są na start ukryte, dopóki ich nie sprawdzisz i nie pokażesz.',
      {
        label: 'Informacje handlowe',
        text: 'jeden tekst, np. warunki dostawy, dopina się na końcu opisu wielu produktów.',
        big: true,
      },
      'Produkt ma rozmiar i materiały, widoczne też na stronie.',
      'Zdjęcia wyłączone w produkcie nie pokazują się na stronie, choć zostają w panelu.',
    ],
  },
  {
    version: '0.21.8',
    date: '2022-12-07',
    title: 'Kafelki',
    synopsis: 'kwadratowe zdjęcia.',
    changes: ['Zdjęcia na kafelkach produktów są zawsze kwadratowe, więc kafelki mają równą wysokość.'],
  },
  {
    version: '0.21.7',
    date: '2022-12-04',
    title: 'Transport',
    synopsis: 'kosztował zawsze 20 zł, niezależnie od ustawień. Już nie.',
    changes: [
      { label: 'Poprawka', text: 'koszt transportu bierze się z ustawień znakowania zamiast stałych 20 zł.' },
      'Próg transportu 0 oznacza darmowy transport, a puste pole – transport zawsze doliczany.',
    ],
  },
  {
    version: '0.21.6',
    date: '2022-12-03',
    title: 'Dymki',
    synopsis: 'przy ikonach list.',
    changes: ['Ikony w nagłówkach tabel mają dymki wyjaśniające, co oznacza dana kolumna.'],
  },
  {
    version: '0.21.5',
    date: '2022-12-03',
    title: 'Nazewnictwo',
    synopsis: '„Odgórne marże”.',
    changes: [
      '„Globalne marże” nazywają się teraz „Odgórne marże”, a marża produktu jest pokazywana przed marżą na całość.',
    ],
  },
  {
    version: '0.21.4',
    date: '2022-12-02',
    title: 'Kalkulacje',
    synopsis: 'kolory ze schematu.',
    changes: [
      'Marże w Kalkulacjach mają te same kolory co na schemacie ceny, więc łatwiej je dopasować.',
      'Strony zaczynają się wczytywać już po najechaniu na link, więc otwierają się szybciej.',
    ],
  },
  {
    version: '0.21.3',
    date: '2022-12-02',
    title: 'Tabela znakowań',
    synopsis: 'uporządkowana.',
    changes: [
      'Kolumny tabeli znakowań są w bardziej logicznej kolejności, a skróty w nagłówkach mają dymki z pełną nazwą.',
    ],
  },
  {
    version: '0.21.2',
    date: '2022-12-01',
    title: 'Formularz',
    synopsis: '„Wyślij”.',
    changes: [
      'Przycisk „Wyślij” w formularzu zapytania podświetla się po najechaniu, żeby było widać, że da się go kliknąć.',
    ],
  },
  {
    version: '0.21.1',
    date: '2022-12-01',
    title: 'Pole znakowania',
    synopsis: 'także bez znakowania.',
    changes: [
      'Wymiary pola znakowania można podać w samym produkcie, nawet bez wybranego znakowania.',
      'Ceny na stronie mają dopisek „zł” i informację, że zawierają znakowanie.',
    ],
  },
  {
    version: '0.21.0',
    date: '2022-11-30',
    title: 'Wzór cen',
    synopsis: '„Jak wyliczane są ceny?”.',
    changes: [
      'Przycisk w Kalkulacjach pokazuje schemat, z którego widać, jak liczona jest cena produktu i znakowania.',
    ],
  },
  {
    version: '0.20.0',
    date: '2022-11-30',
    title: 'Karta produktu',
    synopsis: 'z cennikiem i zapytaniem. Ta wersja poszła razem z pracą inżynierską.',
    changes: [
      {
        label: 'Karta produktu',
        text: 'galeria, kolory z dostępnością i cennik osobno dla każdego znakowania.',
        big: true,
      },
      { label: 'Zapytaj / Zamów', text: 'formularz pod produktem, którego zapytania trafiają do panelu.', big: true },
      'Znaczki „Nowość” i „Promocja” na kafelkach i karcie produktu.',
    ],
  },
  {
    version: '0.19.3',
    date: '2022-11-29',
    title: 'Linki',
    synopsis: 'w nowej karcie.',
    changes: ['„Link do strony” w edytorach otwiera stronę w nowej karcie, więc panel zostaje otwarty.'],
  },
  {
    version: '0.19.2',
    date: '2022-11-29',
    title: 'Menu i galeria',
    synopsis: 'poprawki.',
    changes: [
      'Podkategorie w menu strony rozwijają się na każdym poziomie, a nie tylko na pierwszym.',
      'Najechanie na miniaturę w galerii produktu zmienia duże zdjęcie.',
    ],
  },
  {
    version: '0.19.1',
    date: '2022-11-29',
    title: 'Menu',
    synopsis: 'podkategorie.',
    changes: ['Kategoria w menu strony rozwija się w listę swoich podkategorii.'],
  },
  {
    version: '0.19.0',
    date: '2022-11-29',
    title: 'Strona publiczna',
    synopsis: 'pierwsza wersja.',
    changes: [
      {
        label: 'Strona',
        text: 'pierwsza wersja strony: nagłówek z menu i wyszukiwarką, strona główna z produktami i karta produktu.',
        big: true,
      },
      'Zalogowany administrator ma na stronie przycisk „Edytuj”, który otwiera dany produkt w panelu.',
    ],
  },
  {
    version: '0.18.0',
    date: '2022-11-24',
    title: 'Menu',
    synopsis: 'edycja menu strony.',
    changes: [
      'Pozycje menu strony ustawia się w panelu; każda prowadzi do strony, kategorii, produktu albo dowolnego linku.',
    ],
  },
  {
    version: '0.17.0',
    date: '2022-11-24',
    title: 'Strony i Fragmenty',
    synopsis: 'edytory treści.',
    changes: [
      { label: 'Strony', text: 'treść podstron (np. regulaminów) edytuje się w panelu, z podglądem.', big: true },
      {
        label: 'Fragmenty',
        text: 'drobne teksty ze strony, np. dane kontaktowe, zmienia się w panelu bez programisty.',
        big: true,
      },
      'Panel ostrzega, gdy ktoś inny zapisał ten sam element w tym samym czasie.',
    ],
  },
  {
    version: '0.16.0',
    date: '2022-11-23',
    title: 'Kolory i Zapytania',
    synopsis: 'listy i edytory.',
    changes: [
      {
        label: 'Kolory',
        text: 'lista wszystkich kolorów produktów, z wyszukiwarką i edytorem nazwy oraz odcienia.',
        big: true,
      },
      {
        label: 'Zapytania',
        text: 'zapytania wysłane ze strony trafiają do panelu, gdzie można je przeczytać.',
        big: true,
      },
      'Napis „WERSJA NIESTABILNA” na stronie zmienia się na „WERSJA DEMO”.',
    ],
  },
  {
    version: '0.15.5',
    date: '2022-11-22',
    title: 'Poprawka',
    synopsis: 'adresy.',
    changes: [{ label: 'Poprawka', text: 'linki nowych produktów i kategorii znów tworzą się poprawnie.' }],
  },
  {
    version: '0.15.4',
    date: '2022-11-22',
    title: 'Nazewnictwo',
    synopsis: '„Utworzenie” i „Aktualizacja”.',
    changes: [
      'Kolumny dat w tabelach nazywają się „Utworzenie” i „Aktualizacja”, tak samo w całym panelu.',
      'Link produktu na stronie tworzy się sam z jego kodu i nazwy.',
    ],
  },
  {
    version: '0.15.3',
    date: '2022-11-22',
    title: 'Listy',
    synopsis: 'pamiętają wszystko w adresie. Strona uprzejmie prosi, żeby z niej nie korzystać.',
    changes: [
      'Link do każdej listy pamięta wyszukiwanie, kategorię i stronę, więc można go wysłać komuś innemu.',
      'Na stronie wisi napis „WERSJA NIESTABILNA – nie korzystaj z serwisu”.',
    ],
  },
  {
    version: '0.15.2',
    date: '2022-11-18',
    title: 'Kolory',
    synopsis: 'zaczątek edytora.',
    changes: ['Początek prac nad edytorem kolorów; na razie nic nie widać.'],
  },
  {
    version: '0.15.1',
    date: '2022-11-18',
    title: 'Hierarchia',
    synopsis: 'przeciąganie kategorii wraca.',
    changes: [
      'Kategorie znów przestawia się, przeciągając je myszką w drzewie, zamiast klikać strzałki.',
      '„Dodaj” przy wybranej kategorii tworzy produkt od razu w niej.',
    ],
  },
  {
    version: '0.15.0',
    date: '2022-11-17',
    title: 'Nakłady',
    synopsis: 'wygodniejsza edycja.',
    changes: [
      'Kolumny nakładów w tabeli znakowań można wstawiać w dowolnym miejscu, przesuwać i usuwać.',
      'Zapis ostrzega, gdy ten sam nakład wpisano dwa razy.',
    ],
  },
  {
    version: '0.14.0',
    date: '2022-11-17',
    title: 'Strona startowa panelu',
    synopsis: 'i przeliczanie po zmianie znakowania.',
    changes: [
      'Strona startowa panelu ma kafelki prowadzące do wszystkich sekcji.',
      'Zapisanie zmienionego znakowania samo przelicza ceny wszystkich produktów, które go używają.',
      'Pierwsza kolumna nakładów w znakowaniu to „Ryczałt”, czyli stała opłata niezależna od ilości.',
    ],
  },
  {
    version: '0.13.2',
    date: '2022-11-15',
    title: 'Znakowania',
    synopsis: 'zapis zmian.',
    changes: ['Zmiany wpisane w tabeli znakowań w Kalkulacjach można wreszcie zapisać.'],
  },
  {
    version: '0.13.1',
    date: '2022-11-15',
    title: 'Porządki',
    synopsis: 'stary plik.',
    changes: ['Usunięty stary, nieużywany plik z kodu; w panelu i na stronie nic się nie zmienia.'],
  },
  {
    version: '0.13.0',
    date: '2022-11-15',
    title: 'Cennik produktu',
    synopsis: 'przebudowa.',
    changes: [
      'Własne ceny wpisane w produkcie dopasowują się do nakładów z jego widoku cen.',
      'Wyjście z Kalkulacji z niezapisanymi marżami pyta, czy na pewno je porzucić.',
    ],
  },
  {
    version: '0.12.0',
    date: '2022-11-12',
    title: 'Znakowania',
    synopsis: 'edycja w Kalkulacjach.',
    changes: [
      {
        label: 'Znakowania',
        text: 'ceny znakowań każdego dostawcy edytuje się w tabeli: przygotowalnia, transport, marża i ceny za nakłady.',
        big: true,
      },
      'Usuwając znakowanie, wybiera się zastępcze dla produktów, które go używały.',
      'Sekcja „Magazyn” w edytorze produktu nazywa się teraz „Warianty”, bo opisuje kolory, a nie tylko stany.',
    ],
  },
  {
    version: '0.11.0',
    date: '2022-11-09',
    title: 'Widoki cen',
    synopsis: 'zapis i usuwanie.',
    changes: [
      'Usuwając widok cen, wybiera się widok zastępczy, a ceny produktów, które go używały, przeliczają się same.',
      'Zmiany w Kalkulacjach zrobione przez innego administratora widać od razu, bez odświeżania.',
    ],
  },
  {
    version: '0.10.1',
    date: '2022-11-08',
    title: 'Aktualizacje',
    synopsis: 'i drobne poprawki list.',
    changes: ['Zmiana liczby pozycji na stronie wraca na pierwszą stronę listy, żeby nie trafić na pustą.'],
  },
  {
    version: '0.10.0',
    date: '2022-11-01',
    title: 'Kalkulacje',
    synopsis: 'marże odgórne i widoki cen.',
    changes: [
      {
        label: 'Marże odgórne',
        text: 'jedna marża ustawiona w Kalkulacjach obowiązuje wszystkie produkty, które nie mają własnej.',
        big: true,
      },
      {
        label: 'Widoki cen',
        text: 'zestawy nakładów (np. 100, 200, 500 sztuk), dla których strona pokazuje ceny.',
        big: true,
      },
    ],
  },
  {
    version: '0.9.0',
    date: '2022-10-28',
    title: 'Wyszukiwarka',
    synopsis: 'w produktach i kategoriach.',
    changes: [
      'Produkty i kategorie można wyszukiwać po nazwie lub kodzie.',
      'Skrót Ctrl+Q przenosi od razu do pola wyszukiwania, bez sięgania po myszkę.',
    ],
  },
  {
    version: '0.8.0',
    date: '2022-10-26',
    title: 'Stronicowanie',
    synopsis: 'listy na strony.',
    changes: [
      'Długie listy produktów i plików są podzielone na strony; liczbę pozycji na stronie wybiera się z listy.',
    ],
  },
  {
    version: '0.7.2',
    date: '2022-10-25',
    title: 'Poprawka',
    synopsis: 'domyślny widok cen.',
    changes: [
      { label: 'Poprawka', text: 'produkt bez wybranego widoku cen dostaje widok domyślny, więc jego ceny się liczą.' },
    ],
  },
  {
    version: '0.7.1',
    date: '2022-10-24',
    title: 'Poprawka',
    synopsis: 'lista pamięta kategorię.',
    changes: [{ label: 'Poprawka', text: 'po odświeżeniu strony lista produktów zostaje w wybranej kategorii.' }],
  },
  {
    version: '0.7.0',
    date: '2022-10-24',
    title: 'Podkategorie',
    synopsis: 'dodawanie i filtry w adresie.',
    changes: [
      'Przycisk „+” przy kategorii dodaje w niej nową podkategorię, bez szukania jej w drzewie.',
      'Kategorii, która ma podkategorie, nie da się usunąć, żeby przypadkiem nie stracić całej gałęzi.',
      'Link do listy produktów zapamiętuje wybraną kategorię i stronę, więc odświeżenie niczego nie gubi.',
    ],
  },
  {
    version: '0.6.1',
    date: '2022-10-22',
    title: 'Poprawka',
    synopsis: 'kategorie główne.',
    changes: [
      {
        label: 'Poprawka',
        text: 'przestawianie kategorii najwyższego poziomu znów się zapisuje, tak jak podkategorii.',
      },
    ],
  },
  {
    version: '0.6.0',
    date: '2022-10-20',
    title: 'Kolejność kategorii',
    synopsis: 'zapisuje się od razu.',
    changes: [
      'Przestawienie kategorii albo przeniesienie jej pod inną od razu zapisuje się w bazie i zmienia menu na stronie.',
    ],
  },
  {
    version: '0.5.5',
    date: '2022-10-20',
    title: 'Na żywo',
    synopsis: 'listy odświeżają się same.',
    changes: [
      'Lista produktów odświeża się sama, gdy inny administrator zapisze lub usunie produkt.',
      'Plik w bibliotece otwiera się w edytorze, w którym można go podmienić na nowy.',
    ],
  },
  {
    version: '0.5.4',
    date: '2022-10-18',
    title: 'Sekcje',
    synopsis: 'każda ma swoją stronę.',
    changes: ['Kolory, Menu, Strony, Fragmenty, Zapytania i API mają już swoje strony, na razie jeszcze puste.'],
  },
  {
    version: '0.5.3',
    date: '2022-10-18',
    title: 'Tabele',
    synopsis: '✓ i ✗.',
    changes: [
      'Kolumny tak/nie w tabelach (np. widoczny, nowość) pokazują ✓ i ✗, więc nie da się ich przypadkiem przestawić.',
    ],
  },
  {
    version: '0.5.2',
    date: '2022-10-18',
    title: 'Kategorie',
    synopsis: 'w nowym edytorze.',
    changes: ['Kategoria otwiera się w wysuwanym edytorze nad listą, tak samo jak produkt.'],
  },
  {
    version: '0.5.1',
    date: '2022-10-17',
    title: 'Pasek edytora',
    synopsis: 'Zapisz i Anuluj na miejscu.',
    changes: ['Przyciski Zapisz, Anuluj i Wróć są w pasku samego edytora, tuż przy tym, co edytujesz.'],
  },
  {
    version: '0.5.0',
    date: '2022-10-15',
    title: 'Nowy edytor',
    synopsis: 'produkt otwiera się nad listą.',
    changes: [
      {
        label: 'Edytor nad listą',
        text: 'produkt otwiera się w panelu wysuwanym nad listą, więc po zamknięciu wracasz dokładnie tam, gdzie byłeś.',
        big: true,
      },
      'Gdy sesja wygaśnie w trakcie edycji, pojawia się logowanie, a niezapisane zmiany nie giną.',
    ],
  },
  {
    version: '0.4.8',
    date: '2022-10-15',
    title: 'Ikony',
    synopsis: 'szybciej.',
    changes: ['Ikony w panelu ładują się dużo szybciej niż wcześniej.'],
  },
  {
    version: '0.4.7',
    date: '2022-10-14',
    title: 'Kategoria',
    synopsis: 'pod własnym adresem.',
    changes: [
      'Każda kategoria otwiera się pod własnym linkiem w panelu, który można komuś wysłać.',
      'Panel ostrzega, gdy ktoś inny właśnie zmienił kategorię, którą edytujesz.',
    ],
  },
  {
    version: '0.4.6',
    date: '2022-10-11',
    title: 'Zapis kategorii',
    synopsis: 'tylko to, co się zmieniło.',
    changes: ['Zapis drzewa kategorii zapisuje tylko te kategorie, które faktycznie zmieniłeś, więc trwa krócej.'],
  },
  {
    version: '0.4.5',
    date: '2022-10-11',
    title: 'Zapis kategorii',
    synopsis: 'wiele naraz.',
    changes: ['Zmiany w kilku kategoriach zapisują się jednym przyciskiem, zamiast każdą kategorię zapisywać osobno.'],
  },
  {
    version: '0.4.4',
    date: '2022-10-11',
    title: 'Zapis kategorii',
    synopsis: 'prace w toku.',
    changes: ['Początek prac nad zapisywaniem drzewa kategorii; na razie nic się nie zmienia.'],
  },
  {
    version: '0.4.3',
    date: '2022-10-07',
    title: 'Kalkulacje',
    synopsis: 'sekcja dostaje nazwę, a usuwanie najpierw pyta, potem usuwa (wcześniej odwrotnie).',
    changes: [
      'Sekcja „Kalkulatory” nazywa się teraz „Kalkulacje”; na razie pokazuje tylko listę znakowań dostawców.',
      'Każde usuwanie najpierw pyta o potwierdzenie, więc jedno przypadkowe kliknięcie niczego nie kasuje.',
    ],
  },
  {
    version: '0.4.2',
    date: '2022-10-06',
    title: 'Edycja kategorii',
    synopsis: 'pierwsza wersja, prosto w tabeli.',
    changes: ['Kategorię można edytować (nazwa, opis, zdjęcie, widoczność) i usunąć prosto z tabeli kategorii.'],
  },
  {
    version: '0.4.1',
    date: '2022-10-06',
    title: 'Strzałki',
    synopsis: 'przestawianie kategorii.',
    changes: [
      'Kategorie można przesuwać strzałkami w górę, w dół i między poziomami, ale zmiana jeszcze się nie zapisuje.',
    ],
  },
  {
    version: '0.4.0',
    date: '2022-10-06',
    title: 'Kategorie',
    synopsis: 'drzewo kategorii przy produktach.',
    changes: [
      {
        label: 'Drzewo kategorii',
        text: 'obok listy produktów; kliknięcie kategorii pokazuje tylko jej produkty, a „Dodaj” tworzy produkt od razu w niej.',
        big: true,
      },
      'Nowa strona Kategorie z całym drzewem i numeracją (1, 1.1, 1.2…), żeby łatwo było się w nim odnaleźć.',
      'Wszystkie ikony w panelu są wymienione na nowe, w jednym spójnym stylu.',
    ],
  },
  {
    version: '0.3.1',
    date: '2022-09-18',
    title: 'Biblioteka',
    synopsis: 'zaznaczanie plików.',
    changes: [
      'W bibliotece można zaznaczyć kilka plików naraz i usunąć je jednym przyciskiem, zamiast po kolei.',
      'Okno wyboru zdjęcia w edytorze pokazuje, który plik jest obecnie wybrany.',
    ],
  },
  {
    version: '0.3.0',
    date: '2022-09-15',
    title: 'Edytor produktu i Biblioteka',
    synopsis: 'kilka miesięcy pracy w jednej wersji.',
    changes: [
      {
        label: 'Edytor produktu',
        text: 'wszystkie dane produktu (nazwa, kod, kategorie, opis, widoczność) edytuje się w jednym oknie.',
        big: true,
      },
      { label: 'Cennik', text: 'cena produktu liczy się sama z ceny zakupu, marży i wybranych znakowań.', big: true },
      { label: 'Warianty', text: 'każdy kolor produktu ma swoją ilość na stanie i swoje zdjęcia.' },
      {
        label: 'Biblioteka',
        text: 'wszystkie pliki są w jednym miejscu; wgrywa się je przeciągnięciem, a w edytorach wybiera z listy.',
        big: true,
      },
      'Gdy inny administrator coś zapisze, pozostali od razu dostają o tym informację.',
    ],
  },
  {
    version: '0.2.2',
    date: '2022-05-20',
    title: 'Porządki',
    synopsis: 'aktualizacja Directusa i nagłówek panelu.',
    changes: [
      'Nagłówek na górze panelu pokazuje nazwę sekcji, w której właśnie jesteś.',
      'Lista produktów pokazuje, kto i kiedy dodał produkt oraz kto go ostatnio zmieniał.',
    ],
  },
  {
    version: '0.2.1',
    date: '2022-04-03',
    title: 'Tabela',
    synopsis: 'lista produktów na wspólnym komponencie tabeli.',
    changes: ['Zmiany w kodzie, po których wszystkie listy w panelu będą działać tak samo; na razie nic nie widać.'],
  },
  {
    version: '0.2.0',
    date: '2022-04-01',
    title: 'Pierwszy panel',
    synopsis: 'logowanie, menu i lista produktów.',
    changes: [
      'Do panelu loguje się własnym e-mailem i hasłem, więc każda zmiana ma podpisanego autora.',
      'Menu boczne ma już wszystkie przyszłe sekcje, choć większość z nich jest jeszcze pusta.',
      'Pierwsza lista produktów, w której można podejrzeć dane pojedynczego produktu.',
    ],
  },
  {
    version: '0.1.0',
    date: '2022-02-27',
    title: 'Start',
    synopsis: 'pusta strona, pusty panel, duże plany.',
    changes: ['Powstaje projekt nowej strony REED i panelu do zarządzania nią; na razie oba są puste.'],
  },
];

export const version = changelog[0].version;
